# Generated by Django 4.1.5 on 2023-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Riboseq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cell_line", models.CharField(max_length=200)),
                ("library_type", models.CharField(max_length=200)),
                ("treatment", models.CharField(max_length=200)),
            ],
        ),
    ]
