# Generated by Django 4.1.5 on 2023-01-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiboseqSampel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=200)),
                ("sample_description", models.TextField()),
                (
                    "riboseq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.riboseq"
                    ),
                ),
            ],
        ),
    ]
