# Generated by Django 4.1.5 on 2023-01-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_riboseqsampel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RiboseqSampel",
            new_name="RiboseqSample",
        ),
    ]
