# Generated by Django 4.1.5 on 2023-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_riboseqsampel_riboseqsample"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riboseq",
            name="cell_line",
        ),
        migrations.RemoveField(
            model_name="riboseq",
            name="description",
        ),
        migrations.RemoveField(
            model_name="riboseq",
            name="library_type",
        ),
        migrations.RemoveField(
            model_name="riboseq",
            name="treatment",
        ),
        migrations.AddField(
            model_name="riboseqsample",
            name="cell_line",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="riboseqsample",
            name="library_type",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="riboseqsample",
            name="treatment",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
