# Generated by Django 4.1.5 on 2023-01-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_riboseq_cell_line_remove_riboseq_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RiboseqSample",
            new_name="Sample",
        ),
    ]
