# Generated by Django 4.1.5 on 2023-01-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_riboseqsample_sample"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Riboseq",
            new_name="Data",
        ),
    ]
