# Generated by Django 4.1.5 on 2023-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_riboseq_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
